print("PLEASE ANSWER THE BELOW QUESTIONS\n")
Name = input("Please enter your full name:\n")
Age = input("Please enter your Age:\n")
Location = input("Please enter your location:\n")
print("Thank you for yor information:\n")
print(f"Your Name is {Name}, your age is {Age} and you live in {Location}")
print("THANK YOU")
